### ISSUE TITLE
Evento onclick, attachEvent ou addEventListener ?

### ISSUE THREAD

**Issue by ivandinizaj** [renanmpimentel/no-jquery#10]
Fui criar o eventos.md e fiquei com essa dúvida . Uso `onclick` que é "errado", uso `attachEvent` para compatibilidade para o <IE8 ou uso `addEventListener` para outros navegadores ?

**Comment by renanmpimentel** [comment]
Cara, eu acho que a ideia é IE9+, até porque a versão 2.x do jQuery, eles não dão suporte para IE8- 

http://jquery.com/browser-support/

Então, eu voto em `addEventListener()`

**Comment by ivandinizaj** [comment]
começarei !
