### ISSUE TITLE
Seria interessante a inclusão de Plugins ?

### ISSUE THREAD

**Issue by ivandinizaj** [renanmpimentel/no-jquery#4]
O que mais vejo é slides, efeito parallax, ligthbox desenvolvidos em JQuery(isso me dói no coração). Acham interessante disponibilizar aqui uma lista desses plugins feito em PureJS ?

**Comment by renanmpimentel** [comment]
Acho que rola sim, podemos adicionar no README.md uma lista ou adicionar a lista em um area especifica ..

**Comment by ivandinizaj** [comment]
fechou .

**Comment by renanmpimentel** [comment]
@ivandinizaj tu cria essa pasta/file ?

**Comment by ivandinizaj** [comment]
Já estou criando @renanmpimentel !
